### Get all bonos
GET http://localhost:3001/api/bonos

### Get a bono by id
GET http://localhost:3001/api/bonos/65597e60ed98d10807cbd81e

### Delete a bono by id
DELETE http://localhost:3001/api/bonos/65597e8d3eefac6932c40b3e

### Post a bono
POST http://localhost:3001/api/bonos
Content-Type: application/json

{
    "content": "New content for test user",
    "important": true,
    "userId": "655abc5676015316a2967c4d"
}

### Put a bono
PUT http://localhost:3001/api/bonos/65597e953eefac6932c40b40
Content-Type: application/json

{
    "content": "New new content 2"
}