### get all asigned bonos
GET http://localhost:3001/api/bonos-asignados


### get bono by id
GET http://localhost:3001/api/bonos-asignados/655bff16ba3fbb839073761f


### delete bono by id
DELETE http://localhost:3001/api/bonos-asignados/655bff16ba3fbb839073761f

### asign bono to student
POST http://localhost:3001/api/bonos-asignados
Content-Type: application/json

{
    "codigoEstudiante": "2260422"
}

### get bono asigned today
GET http://localhost:3001/api/bonos-asignados/today


### check if bono was asigned today
GET http://localhost:3001/api/bonos-asignados/today/655bffe2b36f9bb671a7a261


